version: '3.6'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/server
      - /server/node_modules
    ports:
      - 4000:4000
